In [26]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import json
import torch
import torch.nn as nn
import torch.nn.functional as F



In [27]:
# read json file
file = 'data.json'
with open(file) as f:
    data = json.load(f)

data

{'gameRemainTime': 0,
 'id': 814,
 'map_info': {'bombs': [{'col': 20,
    'playerId': 'player2-xxx',
    'remainTime': 1999,
    'row': 1}],
  'gameStatus': None,
  'human': [{'curedRemainTime': 0,
    'direction': 2,
    'infected': True,
    'position': {'col': 1, 'row': 10}},
   {'curedRemainTime': 0,
    'direction': 4,
    'infected': True,
    'position': {'col': 1, 'row': 8}},
   {'curedRemainTime': 0,
    'direction': 4,
    'infected': True,
    'position': {'col': 13, 'row': 4}},
   {'curedRemainTime': 0,
    'direction': 1,
    'infected': True,
    'position': {'col': 11, 'row': 12}},
   {'curedRemainTime': 0,
    'direction': 4,
    'infected': True,
    'position': {'col': 19, 'row': 9}},
   {'curedRemainTime': 0,
    'direction': 2,
    'infected': True,
    'position': {'col': 19, 'row': 9}},
   {'curedRemainTime': 0,
    'direction': 4,
    'infected': True,
    'position': {'col': 1, 'row': 10}},
   {'curedRemainTime': 0,
    'direction': 1,
    'infected': True,
    

In [28]:
mapp = data['map_info']['map']

In [29]:
mapp = np.array(mapp)

In [30]:
mapp

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1],
       [1, 1, 0, 0, 0, 1, 7, 1, 0, 0, 0, 2, 1, 2, 0, 0, 0, 0, 0, 0, 0, 2,
        0, 0, 1, 1],
       [1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0,
        0, 1, 2, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 6, 0, 0, 0, 0,
        2, 2, 0, 1],
       [1, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2,
        2, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 2, 1, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 1, 2,
        0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 2, 2, 0,
        0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 6, 2, 2, 0, 0, 0, 2, 1, 0, 0,
        0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 2, 2, 2, 0, 0, 0, 1, 2, 0, 1, 0,
        0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 2,
        0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 2, 0, 6, 0, 2, 0, 0, 0, 

In [31]:
np.unique(mapp)

array([0, 1, 2, 6, 7])

In [32]:
# mapp[0,1]

In [33]:
mapp[mapp == 6] = 3
mapp[mapp == 7] = 4


In [34]:
np.unique(mapp)

array([0, 1, 2, 3, 4])

In [35]:
mapp = torch.from_numpy(mapp)

In [36]:
mapp = F.one_hot(mapp)

In [37]:
mapp.shape

torch.Size([14, 26, 5])

In [39]:
mapp

tensor([[[0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0],
         ...,
         [0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0]],

        [[0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0],
         [1, 0, 0, 0, 0],
         ...,
         [1, 0, 0, 0, 0],
         [0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0]],

        [[0, 1, 0, 0, 0],
         [1, 0, 0, 0, 0],
         [0, 1, 0, 0, 0],
         ...,
         [0, 1, 0, 0, 0],
         [0, 0, 1, 0, 0],
         [0, 1, 0, 0, 0]],

        ...,

        [[0, 1, 0, 0, 0],
         [1, 0, 0, 0, 0],
         [0, 1, 0, 0, 0],
         ...,
         [0, 1, 0, 0, 0],
         [1, 0, 0, 0, 0],
         [0, 1, 0, 0, 0]],

        [[0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0],
         [1, 0, 0, 0, 0],
         ...,
         [1, 0, 0, 0, 0],
         [0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0]],

        [[0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0],
         ...,
         [0, 1, 0, 0, 0],
        

In [40]:
bombs = data['map_info']['bombs']

In [44]:
bombs

[{'col': 20, 'playerId': 'player2-xxx', 'remainTime': 1999, 'row': 1}]

In [46]:
data['map_info'].keys()

dict_keys(['bombs', 'gameStatus', 'human', 'humanSpeed', 'map', 'players', 'size', 'spoils', 'virusSpeed', 'viruses'])

In [49]:
data['map_info']['size']

{'cols': 26, 'rows': 14}

In [53]:
map_bombs = torch.zeros(data['map_info']['size']['rows'], data['map_info']['size']['cols'])

In [54]:
map_bombs.shape

torch.Size([14, 26])

In [55]:
mapp.shape

torch.Size([14, 26, 5])

In [56]:
# for bomb in bombs:
#     map_bombs[bomb['row'], bomb['col']] = int(bomb['remainTime'])

In [96]:
map_bombs

tensor([[   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
            0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
            0.,    0.,    0.,    0.,    0.,    0.],
        [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
            0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
         1999.,    0.,    0.,    0.,    0.,    0.],
        [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
            0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
            0.,    0.,    0.,    0.,    0.,    0.],
        [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
            0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
            0.,    0.,    0.,    0.,    0.,    0.],
        [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
            0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
  

In [61]:
a = map_bombs.numpy()

In [98]:
map_bombs.shape

torch.Size([14, 26])

In [62]:
spoils = data['map_info']['spoils']

In [63]:
map_spoils = torch.zeros(data['map_info']['size']['rows'], data['map_info']['size']['cols'])

In [77]:
map_spoils.dtype

torch.float32

In [74]:
for spoil in spoils:
    map_spoils[spoil['row'], spoil['col']] = int(spoil['spoil_type'])

In [88]:
map_spoils = map_spoils.long()

In [89]:
map_spoils

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
         0, 0],
        [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0],
        [0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         2, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2,
         0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 1, 0,
         0, 0],
        [0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 2, 0, 0, 2, 0, 0,
         0, 0],
        [0, 1, 0, 0, 2, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 2, 2, 1, 0, 0, 0, 0, 0, 0,
         0, 0],
        [0, 2, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0,
         0, 0],
        [0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 0, 0,
         0, 0],
        [0, 0, 0, 0, 0, 0, 0, 

In [90]:
map_spoils[map_spoils == 3] = 0
map_spoils[map_spoils == 4] = 1
map_spoils[map_spoils == 5] = 2


In [91]:
map_spoils.dtype

torch.int64

In [93]:
one_hot_map_spoils = F.one_hot(map_spoils, num_classes=3)

In [99]:
one_hot_map_spoils.shape

torch.Size([14, 26, 3])

In [102]:
data['map_info']['players']

[{'box': 0,
  'currentPosition': {'col': 24, 'row': 7},
  'delay': 1200,
  'humanCured': 0,
  'humanInfected': 0,
  'humanSaved': 0,
  'id': 'player1-xxx',
  'lives': 1000,
  'pill': 0,
  'pillUsed': 0,
  'power': 1,
  'quarantine': 0,
  'score': 0,
  'spawnBegin': {'col': 24, 'row': 7},
  'speed': 230,
  'timeStone': 0,
  'virus': 0,
  'virusInfected': 0},
 {'box': 11,
  'currentPosition': {'col': 20, 'row': 1},
  'delay': 1200,
  'humanCured': 2,
  'humanInfected': 1,
  'humanSaved': 3,
  'id': 'player2-xxx',
  'lives': 992,
  'pill': 0,
  'pillUsed': 2,
  'power': 1,
  'quarantine': 2,
  'score': 2,
  'spawnBegin': {'col': 1, 'row': 6},
  'speed': 230,
  'timeStone': 0,
  'virus': 0,
  'virusInfected': 1}]

In [160]:

map_bombs_power = torch.zeros(data['map_info']['size']['rows'], data['map_info']['size']['cols'])
for i in range(len(data['map_info']['players'])):
    power = data['map_info']['players'][i]['power']
    player_id = data['map_info']['players'][i]['id']
    for bomb in bombs:
        if bomb['playerId'] == player_id:
            remainTime = int(bomb['remainTime'])
            # map_bombs_power[bomb['row'], bomb['col']] = remainTime
            print(power)
            for p in range(power+3):
                map_bombs_power[bomb['row']+p, bomb['col']] = remainTime
                map_bombs_power[bomb['row'], bomb['col']+p] = remainTime
                _row = max(0, bomb['row']-p)
                _col = max(0, bomb['col']-p)
                map_bombs_power[_row, bomb['col']] = remainTime
                map_bombs_power[bomb['row'], _col] = remainTime


1


In [162]:

map_bombs_power

tensor([[   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
            0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
         1999.,    0.,    0.,    0.,    0.,    0.],
        [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
            0.,    0.,    0.,    0.,    0.,    0.,    0., 1999., 1999., 1999.,
         1999., 1999., 1999., 1999.,    0.,    0.],
        [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
            0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
         1999.,    0.,    0.,    0.,    0.,    0.],
        [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
            0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
         1999.,    0.,    0.,    0.,    0.,    0.],
        [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
            0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
  

In [163]:
map_bombs_power.shape

torch.Size([14, 26])

In [164]:
map_bombs_power.dtype

torch.float32

In [165]:
a = map_bombs_power.numpy()

In [166]:

PLAYER_ID = "player1-xxx"
map_enemy = torch.zeros(data['map_info']['size']['rows'], data['map_info']['size']['cols'])
for i in range(len(data['map_info']['players'])):
    if data['map_info']['players'][i]['id'] != PLAYER_ID:
        player_id = data['map_info']['players'][i]['id']
        map_enemy[data['map_info']['players'][i]['currentPosition']['row'], data['map_info']['players'][i]['currentPosition']['col']] = 1
map_current_player = torch.zeros(data['map_info']['size']['rows'], data['map_info']['size']['cols'])
for i in range(len(data['map_info']['players'])):
    if data['map_info']['players'][i]['id'] == PLAYER_ID:
        player_id = data['map_info']['players'][i]['id']
        map_current_player[data['map_info']['players'][i]['currentPosition']['row'], data['map_info']['players'][i]['currentPosition']['col']] = 1

In [169]:
map_enemy.shape

torch.Size([14, 26])

In [175]:
# concat everything
print('mapp.shape: ', mapp.shape)
print('one_hot_map_spoils.shape: ', one_hot_map_spoils.shape)
print('map_bombs_power.shape: ', map_bombs_power.shape)
print('map_enemy.shape: ', map_enemy.shape)
print('map_current_player.shape: ', map_current_player.shape)

mapp.shape:  torch.Size([14, 26, 5])
one_hot_map_spoils.shape:  torch.Size([14, 26, 3])
map_bombs_power.shape:  torch.Size([14, 26])
map_enemy.shape:  torch.Size([14, 26])
map_current_player.shape:  torch.Size([14, 26])


In [177]:
map_all = torch.cat((mapp, one_hot_map_spoils, map_bombs_power[...,None], map_enemy[...,None], map_current_player[...,None]), dim=2)

In [178]:
map_all.shape

torch.Size([14, 26, 11])