In [50]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import json
import torch
import torch.nn as nn
import torch.nn.functional as F



In [51]:
# read json file
file = 'data.json'
with open(file) as f:
    data = json.load(f)

data

{'gameRemainTime': 0,
 'id': 2161,
 'map_info': {'bombs': [],
  'gameStatus': None,
  'human': [{'curedRemainTime': 0,
    'direction': 3,
    'infected': True,
    'position': {'col': 17, 'row': 11}},
   {'curedRemainTime': 0,
    'direction': 1,
    'infected': True,
    'position': {'col': 9, 'row': 5}},
   {'curedRemainTime': 0,
    'direction': 3,
    'infected': True,
    'position': {'col': 23, 'row': 6}}],
  'humanSpeed': 70,
  'map': [[1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1],
   [1,
    2,
    2,
    2,
    2,
    2,
    0,
    1,
    0,
    2,
    0,
    2,
    2,
    2,
    2,
    0,
    2,
    0,
    1,
    0,
    2,
    2,
    2,
    2,
    2,
    1],
   [1,
    2,
    0,
    0,
    0,
    2,
    0,
    1,
    0,
    2,
    0,
    2,
    0,
    0,
    2,
    0,
    2,
    0,
    1,
    0,
    2,
    0,
    0,
    0,
    2,
    1],
   [1,

In [52]:
mapp = data['map_info']['map']

In [53]:
mapp = np.array(mapp)

In [54]:
mapp

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1],
       [1, 2, 2, 2, 2, 2, 0, 1, 0, 2, 0, 2, 2, 2, 2, 0, 2, 0, 1, 0, 2, 2,
        2, 2, 2, 1],
       [1, 2, 0, 0, 0, 2, 0, 1, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0, 1, 0, 2, 0,
        0, 0, 2, 1],
       [1, 2, 0, 6, 0, 2, 0, 1, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0, 1, 0, 2, 0,
        6, 0, 2, 1],
       [1, 2, 0, 0, 0, 2, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 2, 0,
        0, 0, 2, 1],
       [1, 2, 2, 2, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 2,
        2, 2, 2, 1],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 1],
       [1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 1],
       [1, 2, 2, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 2,
        2, 2, 2, 1],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0,
        0, 0, 2, 1],
       [1, 2, 0, 6, 0, 2, 0, 1, 2, 2, 2, 2, 2, 0, 

In [55]:
np.unique(mapp)

array([0, 1, 2, 6, 7])

In [56]:
mapp[mapp == 6] = 3
mapp[mapp == 7] = 4


In [57]:
np.unique(mapp)

array([0, 1, 2, 3, 4])

In [58]:
mapp = torch.from_numpy(mapp)

In [61]:
mapp = F.one_hot(mapp)

In [63]:
mapp.shape

torch.Size([14, 26, 5])

In [64]:
mapp

tensor([[[0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0],
         ...,
         [0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0]],

        [[0, 1, 0, 0, 0],
         [0, 0, 1, 0, 0],
         [0, 0, 1, 0, 0],
         ...,
         [0, 0, 1, 0, 0],
         [0, 0, 1, 0, 0],
         [0, 1, 0, 0, 0]],

        [[0, 1, 0, 0, 0],
         [0, 0, 1, 0, 0],
         [1, 0, 0, 0, 0],
         ...,
         [1, 0, 0, 0, 0],
         [0, 0, 1, 0, 0],
         [0, 1, 0, 0, 0]],

        ...,

        [[0, 1, 0, 0, 0],
         [0, 0, 1, 0, 0],
         [1, 0, 0, 0, 0],
         ...,
         [1, 0, 0, 0, 0],
         [0, 0, 1, 0, 0],
         [0, 1, 0, 0, 0]],

        [[0, 1, 0, 0, 0],
         [1, 0, 0, 0, 0],
         [1, 0, 0, 0, 0],
         ...,
         [0, 0, 1, 0, 0],
         [0, 0, 1, 0, 0],
         [0, 1, 0, 0, 0]],

        [[0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0],
         ...,
         [0, 1, 0, 0, 0],
        